#!/bin/bash
set -e

echo "📊 Kiro Users Report — One-Click Deploy"
echo "================================"

# ── Prerequisites ──
command -v terraform >/dev/null 2>&1 || { echo "❌ Terraform is required. Install: https://www.terraform.io/downloads"; exit 1; }
command -v aws >/dev/null 2>&1 || { echo "❌ AWS CLI is required. Install: https://aws.amazon.com/cli/"; exit 1; }

# ── Step 1: Terraform setup ──
echo ""
echo "📝 Step 1: Terraform configuration"

if [ ! -f "terraform/terraform.tfvars" ]; then
    echo "Creating terraform.tfvars from example..."
    cp terraform/terraform.tfvars.example terraform/terraform.tfvars
    echo ""
    echo "⚠️  Please edit terraform/terraform.tfvars with your values:"
    echo "   - aws_account_id"
    echo "   - s3_bucket_name"
    echo "   - glue_database_name"
    echo "   - identity_store_id (required, for username lookup)"
    echo ""
    read -p "Press Enter when ready to continue..."
fi

# ── Step 2: Terraform init + apply ──
echo ""
echo "🔧 Step 2: Deploying infrastructure"

terraform -chdir=terraform init
terraform -chdir=terraform plan

read -p "Apply this plan? (yes/no): " confirm
if [ "$confirm" != "yes" ]; then
    echo "Cancelled."
    exit 0
fi

terraform -chdir=terraform apply -auto-approve

# ── Step 3: Extract outputs → app/.env ──
echo ""
echo "⚙️  Step 3: Configuring application"

AWS_REGION=$(terraform -chdir=terraform output -raw aws_region)
DATABASE_NAME=$(terraform -chdir=terraform output -raw glue_database_name)
ATHENA_OUTPUT=$(terraform -chdir=terraform output -raw athena_output_location)
IDENTITY_STORE_ID=$(terraform -chdir=terraform output -raw identity_store_id)
ATHENA_WORKGROUP=$(terraform -chdir=terraform output -raw athena_workgroup)

cat > app/.env << EOF
# Generated by deploy.sh on $(date)
AWS_REGION=${AWS_REGION}
ATHENA_DATABASE=${DATABASE_NAME}
ATHENA_OUTPUT_BUCKET=${ATHENA_OUTPUT}
ATHENA_WORKGROUP=${ATHENA_WORKGROUP}
IDENTITY_STORE_ID=${IDENTITY_STORE_ID}
EOF

echo "✅ Created app/.env"
cat app/.env

# ── Step 4: Run Glue crawler ──
echo ""
echo "🕷️  Step 4: Running Glue crawler"

CRAWLER_NAME=$(terraform -chdir=terraform output -raw glue_crawler_name)
aws glue start-crawler --name "${CRAWLER_NAME}"

echo "Waiting for crawler to finish (may take a few minutes)..."
while true; do
    STATUS=$(aws glue get-crawler --name "${CRAWLER_NAME}" --query 'Crawler.State' --output text)
    if [ "$STATUS" = "READY" ]; then break; fi
    echo "  Crawler status: $STATUS"
    sleep 10
done
echo "✅ Crawler completed"

# ── Step 5: Create cleaned Athena View ──
echo ""
echo "🔍 Step 5: Creating cleaned Athena View"

VIEW_QUERY_ID=$(terraform -chdir=terraform output -raw create_view_query_id)
# Retrieve the named query SQL and execute it
VIEW_SQL=$(aws athena get-named-query --named-query-id "${VIEW_QUERY_ID}" --query 'NamedQuery.QueryString' --output text)
EXEC_ID=$(aws athena start-query-execution \
    --query-string "${VIEW_SQL}" \
    --query-execution-context "Database=${DATABASE_NAME}" \
    --work-group "${ATHENA_WORKGROUP}" \
    --query 'QueryExecutionId' --output text)

echo "  Waiting for view creation (query ${EXEC_ID})..."
while true; do
    VIEW_STATUS=$(aws athena get-query-execution --query-execution-id "${EXEC_ID}" --query 'QueryExecution.Status.State' --output text)
    if [ "$VIEW_STATUS" = "SUCCEEDED" ]; then break; fi
    if [ "$VIEW_STATUS" = "FAILED" ] || [ "$VIEW_STATUS" = "CANCELLED" ]; then
        echo "❌ View creation failed: ${VIEW_STATUS}"
        aws athena get-query-execution --query-execution-id "${EXEC_ID}" --query 'QueryExecution.Status.StateChangeReason' --output text
        exit 1
    fi
    sleep 2
done
echo "✅ Cleaned view created: kiro_user_report_cleaned"

# Write the view name to .env so the app uses it
echo "GLUE_TABLE_NAME=kiro_user_report_cleaned" >> app/.env

# ── Step 6: Launch dashboard ──
echo ""
echo "🚀 Step 6: Launching dashboard"
echo ""
echo "Run the following command to start the dashboard:"
echo ""
echo "cd app && python -m venv venv && source venv/bin/activate && pip install -r requirements.txt && streamlit run app.py"
echo ""
echo "✅ Deploy complete!"
